<?php

namespace App\Admin;

use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

final class PrivilegioRoles extends AbstractAdmin
{

    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->tab('General')
                ->with('General',  ['class' => 'col-lg-12'])
                    ->add('descripcion', null, ['label' => 'Nombre', 'required' => true])
                ->end()

                ->with('Monitor de auditoria',  ['class' => 'col-lg-4'])
                    ->add('monitorAuditoriaSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('exportMonitorAuditoriaSn', CheckboxType::class, ['label' => 'Exportar datos', 'required' => false])
                ->end()

                ->with('Administración',  ['class' => 'col-lg-4'])
                    ->add('administracionSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                ->end()

                ->with('Intranet',  ['class' => 'col-lg-4'])
                    ->add('intranetSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                ->end()

                ->with('Exportación de datos',  ['class' => 'col-lg-3'])
                    ->add('buscadorSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('addBuscadorSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editBuscadorSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('copyBuscadorSn', CheckboxType::class, ['label' => 'Copiar', 'required' => false])
                    ->add('executeBuscadorSn', CheckboxType::class, ['label' => 'Ejecutar', 'required' => false])
                    ->add('deleteBuscadorSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportBuscadorSn', CheckboxType::class, ['label' => 'Exportar datos', 'required' => false])
                ->end()

                ->with('Plantillas',  ['class' => 'col-lg-3'])
                    ->add('gdocSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('addGdocSn', CheckboxType::class, ['label' => 'Crear carpeta', 'required' => false])
                    ->add('editGdocSn', CheckboxType::class, ['label' => 'Editar carpeta', 'required' => false])
                    ->add('deleteGdocSn', CheckboxType::class, ['label' => 'Eliminar carpeta', 'required' => false])
                    ->add('addGdocFileSn', CheckboxType::class, ['label' => 'Crear plantilla', 'required' => false])
                    ->add('openGdocFileSn', CheckboxType::class, ['label' => 'Abrir plantilla', 'required' => false])
                    ->add('downGdocFileSn', CheckboxType::class, ['label' => 'Descargar plantilla', 'required' => false])
                    ->add('deleteGdocFileSn', CheckboxType::class, ['label' => 'Eliminar plantilla', 'required' => false])
                ->end()

		        ->with('Citaciones',  ['class' => 'col-lg-3'])
			        ->add('citacionSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
			        ->add('addCitacionSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
			        ->add('editCitacionSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
			        ->add('deleteCitacionSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
		        ->end()

                ->with('Mantenimiento reconocimientos',  ['class' => 'col-lg-3'])
                    ->add('mantenimientoReconocimientosSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('mantenimientoSerieRespuestaSn', CheckboxType::class, ['label' => 'Series de respuesta', 'required' => false])
                    ->add('mantenimientoPreguntasSn', CheckboxType::class, ['label' => 'Preguntas', 'required' => false])
                    ->add('mantenimientoSubPreguntasSn', CheckboxType::class, ['label' => 'Subpreguntas', 'required' => false])
                    ->add('mantenimientoConsejosMedicosSn', CheckboxType::class, ['label' => 'Consejos médicos', 'required' => false])
                    ->add('mantenimientoRespuestasSn', CheckboxType::class, ['label' => 'Respuestas', 'required' => false])
                    ->add('mantenimientoFormulasSn', CheckboxType::class, ['label' => 'Formulas', 'required' => false])
                    ->add('mantenimientoCuestionariosSn', CheckboxType::class, ['label' => 'Cuestionarios', 'required' => false])
                ->end()

                ->with('Correos enviados',  ['class' => 'col-lg-3'])
                    ->add('logEnvioMailSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('enviarCorreoMasivoSn', CheckboxType::class, ['label' => 'Envío masivo', 'required' => false])
                ->end()

                ->with('Aviso vencimiento aptitud',  ['class' => 'col-lg-3'])
                    ->add('avisoVencimientoAptitud', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                ->end()

            ->end()

            ->tab('Administración')

                ->with('Empresas',  ['class' => 'col-lg-3'])
                    ->add('empresaSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('viewEmpresaSn', CheckboxType::class, ['label' => 'Ver', 'required' => false])
                    ->add('addEmpresaSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editEmpresaSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteEmpresaSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportEmpresaSn', CheckboxType::class, ['label' => 'Exportar datos', 'required' => false])
                ->end()

                ->with('Centros de trabajo',  ['class' => 'col-lg-3'])
                    ->add('centroTrabajoSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('viewCentroTrabajoSn', CheckboxType::class, ['label' => 'Ver', 'required' => false])
                    ->add('addCentroTrabajoSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editCentroTrabajoSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteCentroTrabajoSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportCentroTrabajoSn', CheckboxType::class, ['label' => 'Exportar datos', 'required' => false])
                ->end()

                ->with('Trabajadores',  ['class' => 'col-lg-3'])
                    ->add('trabajadorSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('viewTrabajadorSn', CheckboxType::class, ['label' => 'Ver', 'required' => false])
                    ->add('addTrabajadorSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editTrabajadorSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteTrabajadorSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportTrabajadorSn', CheckboxType::class, ['label' => 'Exportar datos', 'required' => false])
                    ->add('importTrabajadorSn', CheckboxType::class, ['label' => 'Importar trabajadores', 'required' => false])
                ->end()

                ->with('Renovaciones',  ['class' => 'col-lg-3'])
                    ->add('renovacionSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('viewRenovacionSn', CheckboxType::class, ['label' => 'Ver', 'required' => false])
                    ->add('renovarRenovacionSn', CheckboxType::class, ['label' => 'Renovar', 'required' => false])
                    ->add('addRenovacionSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editRenovacionSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteRenovacionSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportRenovacionSn', CheckboxType::class, ['label' => 'Exportar datos', 'required' => false])
                ->end()

                ->with('Pagos pendientes',  ['class' => 'col-lg-3'])
                    ->add('pagoPendienteSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('viewPagoPendienteSn', CheckboxType::class, ['label' => 'Ver', 'required' => false])
                    ->add('addPagoPendienteSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editPagoPendienteSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deletePagoPendienteSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportPagoPendienteSn', CheckboxType::class, ['label' => 'Exportar datos', 'required' => false])
                    ->add('facturarPagoPendienteSn', CheckboxType::class, ['label' => 'Facturar', 'required' => false])
                ->end()

                ->with('Datos bancarios',  ['class' => 'col-lg-3'])
                    ->add('datosBancariosSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('viewDatosBancariosSn', CheckboxType::class, ['label' => 'Ver', 'required' => false])
                    ->add('addDatosBancariosSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editDatosBancariosSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteDatosBancariosSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportDatosBancariosSn', CheckboxType::class, ['label' => 'Exportar datos', 'required' => false])
                ->end()

                ->with('Remesas',  ['class' => 'col-lg-3'])
                    ->add('remesaSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('addRemesaSn', CheckboxType::class, ['label' => 'Generar remesa', 'required' => false])
                    ->add('deleteRemesaSn', CheckboxType::class, ['label' => 'Eliminar remesa', 'required' => false])
                    ->add('downRemesaSn', CheckboxType::class, ['label' => 'Descargar remesa', 'required' => false])
                    ->add('exportRemesaSn', CheckboxType::class, ['label' => 'Exportar datos', 'required' => false])
                ->end()

                ->with('Contratos',  ['class' => 'col-lg-3'])
                    ->add('contratoSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('viewContratoSn', CheckboxType::class, ['label' => 'Ver', 'required' => false])
                    ->add('printContratoSn', CheckboxType::class, ['label' => 'Imprimir', 'required' => false])
                    ->add('addContratoSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editContratoSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteContratoSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportContratoSn', CheckboxType::class, ['label' => 'Exportar datos', 'required' => false])
                    ->add('renovarContratoMultipleSn', CheckboxType::class, ['label' => 'Renovar contratos múltiple', 'required' => false])
                    ->add('sendContratoSn', CheckboxType::class, ['label' => 'Enviar', 'required' => false])
                ->end()

                ->with('Certificaciones',  ['class' => 'col-lg-3'])
                    ->add('addCertificacionSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('printCertificacionSn', CheckboxType::class, ['label' => 'Imprimir', 'required' => false])
                    ->add('deleteCertificacionSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportCertificacionSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                ->end()

                ->with('Tarifas',  ['class' => 'col-lg-3'])
                    ->add('addTarifaSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editTarifaSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteTarifaSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportTarifaSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                ->end()

                ->with('Modelo 347',  ['class' => 'col-lg-3'])
                    ->add('addModelo347Sn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('printModelo347Sn', CheckboxType::class, ['label' => 'Imprimir', 'required' => false])
                    ->add('deleteModelo347Sn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportModelo347Sn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                    ->add('sendModelo347Sn', CheckboxType::class, ['label' => 'Enviar', 'required' => false])
                ->end()

                ->with('Notificaciones',  ['class' => 'col-lg-3'])
                    ->add('addNotificacionSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('printNotificacionSn', CheckboxType::class, ['label' => 'Imprimir', 'required' => false])
                    ->add('deleteNotificacionSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportNotificacionSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                    ->add('sendNotificacionSn', CheckboxType::class, ['label' => 'Enviar', 'required' => false])
                ->end()

                ->with('Balance económico',  ['class' => 'col-lg-3'])
                    ->add('balanceEconomicoSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('viewBalanceEconomicoSn', CheckboxType::class, ['label' => 'Ver', 'required' => false])
                    ->add('addGiroBalanceEconomicoSn', CheckboxType::class, ['label' => 'Generar giro', 'required' => false])
                    ->add('editGiroBalanceEconomicoSn', CheckboxType::class, ['label' => 'Editar giro', 'required' => false])
                    ->add('deleteGiroBalanceEconomicoSn', CheckboxType::class, ['label' => 'Eliminar giro', 'required' => false])
                    ->add('exportGiroBalanceEconomicoSn', CheckboxType::class, ['label' => 'Exportar datos', 'required' => false])
                    ->add('addTransferenciaBalanceEconomicoSn', CheckboxType::class, ['label' => 'Generar transferencia', 'required' => false])
                    ->add('deleteTransferenciaBalanceEconomicoSn', CheckboxType::class, ['label' => 'Eliminar transferencia', 'required' => false])
                    ->add('addEntradaBalanceEconomicoSn', CheckboxType::class, ['label' => 'Añadir entrada', 'required' => false])
                    ->add('editEntradaBalanceEconomicoSn', CheckboxType::class, ['label' => 'Editar entrada', 'required' => false])
                    ->add('deleteEntradaBalanceEconomicoSn', CheckboxType::class, ['label' => 'Eliminar entrada', 'required' => false])
                ->end()

                ->with('Facturación',  ['class' => 'col-lg-3'])
                    ->add('facturacionSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('viewFacturacionSn', CheckboxType::class, ['label' => 'Ver', 'required' => false])
                    ->add('addFacturacionSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editFacturacionSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteFacturacionSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportFacturacionSn', CheckboxType::class, ['label' => 'Exportar datos', 'required' => false])
                    ->add('printFacturacionSn', CheckboxType::class, ['label' => 'Imprimir facturas', 'required' => false])
                    ->add('sendFacturacionSn', CheckboxType::class, ['label' => 'Enviar facturas', 'required' => false])
                    ->add('addVencimientoFacturacionSn', CheckboxType::class, ['label' => 'Crear vencimiento', 'required' => false])
                    ->add('deleteVencimientoFacturacionSn', CheckboxType::class, ['label' => 'Eliminar vencimiento', 'required' => false])
                    ->add('confirmarVencimientoFacturacionSn', CheckboxType::class, ['label' => 'Confirmar cobro vencimiento', 'required' => false])
                    ->add('facturarContratoMultipleSn', CheckboxType::class, ['label' => 'Facturar contratos múltiple', 'required' => false])
                    ->add('verHuecosFactura', CheckboxType::class, ['label' => 'Ver huecos disponibles', 'required' => false])
                ->end()
            ->end()

            ->tab('Técnico')
                ->with('Agenda',  ['class' => 'col-lg-3'])
                    ->add('agendaTecnicoSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('addAgendaTecnicoSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editAgendaTecnicoSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteAgendaTecnicoSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                ->end()
                ->with('Empresas',  ['class' => 'col-lg-3'])
                    ->add('empresaTecnicoSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('viewEmpresaTecnicoSn', CheckboxType::class, ['label' => 'Ver', 'required' => false])
                    ->add('addEmpresaTecnicoSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editEmpresaTecnicoSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteEmpresaTecnicoSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportEmpresaTecnicoSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                ->end()
                ->with('Evaluaciones',  ['class' => 'col-lg-3'])
                    ->add('evaluacionSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('addEvaluacionSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editEvaluacionSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteEvaluacionSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportEvaluacionSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                    ->add('finalizarEvaluacionSn', CheckboxType::class, ['label' => 'Finalizar', 'required' => false])
                    ->add('printEvaluacionSn', CheckboxType::class, ['label' => 'Imprimir', 'required' => false])
                ->end()
                ->with('Grupos empresa',  ['class' => 'col-lg-3'])
                    ->add('grupoEmpresaSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('addGrupoEmpresaSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editGrupoEmpresaSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteGrupoEmpresaSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportGrupoEmpresaSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                ->end()
                ->with('Puestos de trabajo',  ['class' => 'col-lg-3'])
                    ->add('puestoTrabajoSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('addPuestoTrabajoSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editPuestoTrabajoSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deletePuestoTrabajoSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportPuestoTrabajoSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                ->end()
                ->with('Trabajadores',  ['class' => 'col-lg-3'])
                    ->add('trabajadorTecnicoSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('addTrabajadorTecnicoSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editTrabajadorTecnicoSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteTrabajadorTecnicoSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportTrabajadorTecnicoSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                ->end()
                ->with('Maquina empresa',  ['class' => 'col-lg-3'])
                    ->add('addMaquinaEmpresaSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editMaquinaEmpresaSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteMaquinaEmpresaSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportMaquinaEmpresaSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                ->end()
                ->with('Mantenimiento firmas',  ['class' => 'col-lg-3'])
                    ->add('firmaTecnicoSn', CheckboxType::class, ['label' => 'Acceso/Modificación', 'required' => false])
                ->end()
                ->with('Plan de prevención',  ['class' => 'col-lg-3'])
                    ->add('addPlanPrevencionSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('deletePlanPrevencionSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportPlanPrevencionSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                    ->add('printPlanPrevencionSn', CheckboxType::class, ['label' => 'Imprimir', 'required' => false])
                ->end()
                ->with('Protocolo básico acoso',  ['class' => 'col-lg-3'])
                    ->add('addProtocoloAcosoSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('deleteProtocoloAcosoSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportProtocoloAcosoSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                    ->add('printProtocoloAcosoSn', CheckboxType::class, ['label' => 'Imprimir', 'required' => false])
                ->end()
            ->end()

            ->tab('Médico')
                ->with('Empresas',  ['class' => 'col-lg-3'])
                    ->add('empresaMedicoSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('viewEmpresaMedicoSn', CheckboxType::class, ['label' => 'Ver', 'required' => false])
                    ->add('addEmpresaMedicoSn', CheckboxType::class, ['label' => 'Crear', 'required' => false])
                    ->add('editEmpresaMedicoSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteEmpresaMedicoSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportEmpresaMedicoSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                ->end()
                ->with('Trabajadores',  ['class' => 'col-lg-3'])
                    ->add('trabajadorMedicoSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('editTrabajadorMedicoSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('exportTrabajadorMedicoSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                ->end()
                ->with('Documentación',  ['class' => 'col-lg-3'])
                    ->add('documentacionSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('addDocumentacionSn', CheckboxType::class, ['label' => 'Añadir', 'required' => false])
                    ->add('editDocumentacionSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteDocumentacionSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportDocumentacionSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                ->end()
                ->with('Historial laboral',  ['class' => 'col-lg-3'])
                    ->add('historialLaboralSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('addHistorialLaboralSn', CheckboxType::class, ['label' => 'Añadir', 'required' => false])
                    ->add('editHistorialLaboralSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteHistorialLaboralSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportHistorialLaboralSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                ->end()
                ->with('Revisiones',  ['class' => 'col-lg-3'])
                    ->add('revisionSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('addRevisionSn', CheckboxType::class, ['label' => 'Añadir', 'required' => false])
                    ->add('editRevisionSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteRevisionSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportRevisionSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                    ->add('sendCuestionarioRevisionSn', CheckboxType::class, ['label' => 'Enviar', 'required' => false])
                    ->add('printAptitudRevisionSn', CheckboxType::class, ['label' => 'Imprimir aptitud', 'required' => false])
                    ->add('printResumenRevisionSn', CheckboxType::class, ['label' => 'Imprimir resumen', 'required' => false])
                    ->add('facturarRevisionSn', CheckboxType::class, ['label' => 'Facturar', 'required' => false])
                    ->add('enviarAptitudRevisionSn', CheckboxType::class, ['label' => 'Enviar aptitud', 'required' => false])
                ->end()
                ->with('Investigaciones',  ['class' => 'col-lg-3'])
                    ->add('investigacionSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('addInvestigacionSn', CheckboxType::class, ['label' => 'Añadir', 'required' => false])
                    ->add('editInvestigacionSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteInvestigacionSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportInvestigacionSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                ->end()
                ->with('Enfermedades Profesionales',  ['class' => 'col-lg-3'])
                    ->add('enfermedadProfesionalSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('addEnfermedadProfesionalSn', CheckboxType::class, ['label' => 'Añadir', 'required' => false])
                    ->add('editEnfermedadProfesionalSn', CheckboxType::class, ['label' => 'Editar', 'required' => false])
                    ->add('deleteEnfermedadProfesionalSn', CheckboxType::class, ['label' => 'Eliminar', 'required' => false])
                    ->add('exportEnfermedadProfesionalSn', CheckboxType::class, ['label' => 'Exportar', 'required' => false])
                ->end()
                ->with('Puesto trabajo - Protocolo - Cuestionario',  ['class' => 'col-lg-3'])
                    ->add('puestoTrabajoProtocoloCuestionarioSn', CheckboxType::class, ['label' => 'Acceso', 'required' => false])
                    ->add('protocoloSn', CheckboxType::class, ['label' => 'Protocolo', 'required' => false])
                    ->add('puestoTrabajoProtocoloSn', CheckboxType::class, ['label' => 'Puesto de trabajo - Protocolo', 'required' => false])
                ->end()
                ->with('Mantenimiento firmas',  ['class' => 'col-lg-3'])
                    ->add('firmaMedicoSn', CheckboxType::class, ['label' => 'Acceso/Modificación', 'required' => false])
                ->end()
            ->end()

        ;
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
	        ->add('descripcion', null, ['label' => 'Nombre']);
    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
	        ->addIdentifier('descripcion', null, ['label' => 'Nombre'])
	        ->add('_action', 'actions', array(
		        'actions' => array(
			        'edit' => array(),
			        'delete' => array(),
		        )
	        ));
    }
}